trigger:
- gh-pages

pool:
  vmImage: windows-latest

steps:
- powershell: |
    choco install docfx -y
    $env:MSBuildEnableWorkloadResolver = false
    docfx docs/docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "Documentation"